import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import AuthProvider from "./context/AuthProvider";
import QueryProvider from "./context/QueryProvider";

const poppin = Poppins({ subsets: ["latin"], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], variable: '--font-poppins' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={poppin.variable}>
        <QueryProvider>
          <AuthProvider>
            <Navbar />
            <main className="px-2 md:px-5 container mx-auto">{children}</main>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
